### ISSUE TITLE
 CUDA out of memory

### ISSUE THREAD

**Issue by Uproar197** [shachoi/HANet#3]
**I run the command: 
CUDA_VISIBLE_DEVICES=0,1,2,3 ./scripts/train_r101_o**

and the following are the outputs, errors is about CUDA out of memory,  I **changed the  batch size for training per gpu to 2**, it still wrong. but if i **change the size to 1, there is another error**.  Please help me , **thanks !**

*****************************************
Total world size:  4
Total world size:  4
Total world size:  4
Total world size:  4
My Rank: 1
args.dist_url:tcp://127.0.0.1:8043
My Rank: 2
args.dist_url:tcp://127.0.0.1:8043
My Rank: 3
args.dist_url:tcp://127.0.0.1:8043
My Rank: 0
args.dist_url:tcp://127.0.0.1:8043
Using pytorch sync batch norm
######## CityScapesUniformWithPos #########
Using pytorch sync batch norm
Using pytorch sync batch norm
######## CityScapesUniformWithPos #########
Using pytorch sync batch norm
Logging : ./logs/0103/r101_os8_hanet_64_01/08_25_21/log_2020_08_25_21_00_32_rank_0.log
######## CityScapesUniformWithPos #########
08-25 21:00:33.038 train fine cities: ['train/aachen', 'train/bochum', 'train/bremen', 'train/cologne', 'train/darmstadt', 'train/dusseldorf', 'train/erfurt', 'train/hamburg', 'train/hanover', 'train/jena', 'train/krefeld', 'train/monchengladbach', 'train/strasbourg', 'train/stuttgart', 'train/tubingen', 'train/ulm', 'train/weimar', 'train/zurich']
08-25 21:00:33.058 Cityscapes-train: 2975 images
Unifrom : coarse images
08-25 21:00:33.681 Class Uniform Percentage: 0.5
08-25 21:00:33.682 Class Uniform items per Epoch:2975
08-25 21:00:33.683 cls 0 len 5866
08-25 21:00:33.683 cls 1 len 5184
08-25 21:00:33.683 cls 2 len 5678
08-25 21:00:33.683 cls 3 len 1312
08-25 21:00:33.683 cls 4 len 1723
08-25 21:00:33.683 cls 5 len 5656
08-25 21:00:33.683 cls 6 len 2769
08-25 21:00:33.683 cls 7 len 4860
08-25 21:00:33.683 cls 8 len 5388
08-25 21:00:33.683 cls 9 len 2440
08-25 21:00:33.683 cls 10 len 4722
08-25 21:00:33.683 cls 11 len 3719
08-25 21:00:33.683 cls 12 len 1239
08-25 21:00:33.683 cls 13 len 5075
08-25 21:00:33.683 cls 14 len 444
08-25 21:00:33.683 cls 15 len 348
08-25 21:00:33.683 cls 16 len 188
08-25 21:00:33.684 cls 17 len 575
08-25 21:00:33.684 cls 18 len 2238
08-25 21:00:33.686 val fine cities: ['val/lindau', 'val/frankfurt', 'val/munster']
08-25 21:00:33.688 Cityscapes-val: 500 images
Unifrom : coarse images
Unifrom : coarse images
Unifrom : coarse images
standard cross entropy
standard cross entropy
Model : DeepLabv3+, Backbone : ResNet-101
#### HANet layers 4
standard cross entropy
standard cross entropy
standard cross entropy
standard cross entropy
Model : DeepLabv3+, Backbone : ResNet-101
#### HANet layers 4
Model : DeepLabv3+, Backbone : ResNet-101
#### HANet layers 4
standard cross entropy
standard cross entropy
Model : DeepLabv3+, Backbone : ResNet-101
########### pretrained ##############
output_stride =  8
output_stride =  8
output_stride =  8
output_stride =  8
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
use PosEncoding1D
08-25 21:00:37.312 Model params = 64.807M
-----------use get_optimizer_attention function------------
 ############# HANet Number 4
-----------use get_optimizer_attention function------------
 ############# HANet Number 4
-----gpuid:1-------
-----gpuid:3-------
-----------use get_optimizer_attention function------------
 ############# HANet Number 4
-----gpuid:0-------
-----------use get_optimizer_attention function------------
 ############# HANet Number 4
-----gpuid:2-------
args.snapshot:None
args.snapshot_pe:None
#### iteration 0
args.snapshot:None
args.snapshot_pe:None
#### iteration 0
args.snapshot:None
args.snapshot_pe:None
#### iteration 0
args.snapshot:None
args.snapshot_pe:None
#### iteration 0
i:0
i:0
i:0
i:0
0
length of train loader:186
0
length of train loader:186
0
length of train loader:186
0
length of train loader:186
Traceback (most recent call last):
  File "train.py", line 632, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 632, in <module>
  File "train.py", line 632, in <module>
Traceback (most recent call last):
  File "train.py", line 632, in <module>
    main()
  File "train.py", line 280, in main
    i = train(train_loader, net, optim, epoch, writer, scheduler, args.max_iter, optim_at, scheduler_at)
  File "train.py", line 352, in train
    main()
    outputs = net(inputs, gts=gts, aux_gts=aux_gts, pos=(pos_h, pos_w), attention_loss=requires_attention)
  File "train.py", line 280, in main
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    main()
    main()
  File "train.py", line 280, in main
  File "train.py", line 280, in main
    i = train(train_loader, net, optim, epoch, writer, scheduler, args.max_iter, optim_at, scheduler_at)
  File "train.py", line 352, in train
    i = train(train_loader, net, optim, epoch, writer, scheduler, args.max_iter, optim_at, scheduler_at)
    i = train(train_loader, net, optim, epoch, writer, scheduler, args.max_iter, optim_at, scheduler_at)
  File "train.py", line 352, in train
    result = self.forward(*input, **kwargs)
  File "train.py", line 352, in train
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    outputs = net(inputs, gts=gts, aux_gts=aux_gts, pos=(pos_h, pos_w), attention_loss=requires_attention)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    outputs = net(inputs, gts=gts, aux_gts=aux_gts, pos=(pos_h, pos_w), attention_loss=requires_attention)
    outputs = net(inputs, gts=gts, aux_gts=aux_gts, pos=(pos_h, pos_w), attention_loss=requires_attention)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    result = self.forward(*input, **kwargs)
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
  File "/home/xuangen/myproject/HANet-master/network/deepv3.py", line 416, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    x = self.layer3(x)  # 100
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/myproject/HANet-master/network/deepv3.py", line 416, in forward
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/myproject/HANet-master/network/deepv3.py", line 416, in forward
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/myproject/HANet-master/network/deepv3.py", line 416, in forward
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    x = self.layer3(x)  # 100
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    input = module(input)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    x = self.layer3(x)  # 100
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    x = self.layer3(x)  # 100
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/myproject/HANet-master/network/Resnet.py", line 126, in forward
    input = module(input)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    out = self.bn3(out)
    input = module(input)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    input = module(input)
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
  File "/home/xuangen/myproject/HANet-master/network/Resnet.py", line 126, in forward
    result = self.forward(*input, **kwargs)
    out = self.bn3(out)
  File "/home/xuangen/myproject/HANet-master/network/Resnet.py", line 126, in forward
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 473, in forward
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/myproject/HANet-master/network/Resnet.py", line 126, in forward
    out = self.bn3(out)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
    self.eps, exponential_average_factor, process_group, world_size)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 473, in forward
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/_functions.py", line 54, in forward
    out = self.bn3(out)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    out = torch.batch_norm_elemt(input, weight, bias, mean, invstd, eps)
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 473, in forward
RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 2; 10.92 GiB total capacity; 10.22 GiB already allocated; 125.00 MiB free; 10.26 GiB reserved in total by PyTorch)
    self.eps, exponential_average_factor, process_group, world_size)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/_functions.py", line 54, in forward
    result = self.forward(*input, **kwargs)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 473, in forward
    out = torch.batch_norm_elemt(input, weight, bias, mean, invstd, eps)
RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 3; 10.92 GiB total capacity; 10.22 GiB already allocated; 119.00 MiB free; 10.26 GiB reserved in total by PyTorch)
    self.eps, exponential_average_factor, process_group, world_size)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/_functions.py", line 54, in forward
    out = torch.batch_norm_elemt(input, weight, bias, mean, invstd, eps)
RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 10.92 GiB total capacity; 10.22 GiB already allocated; 124.62 MiB free; 10.26 GiB reserved in total by PyTorch)
    self.eps, exponential_average_factor, process_group, world_size)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/nn/modules/_functions.py", line 54, in forward
    out = torch.batch_norm_elemt(input, weight, bias, mean, invstd, eps)
RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 1; 10.92 GiB total capacity; 10.22 GiB already allocated; 119.00 MiB free; 10.26 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/xuangen/anaconda3/envs/hanet/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xuangen/anaconda3/envs/hanet/bin/python', '-u', 'train.py', '--local_rank=3', '--dataset', 'cityscapes', '--arch', 'network.deepv3.DeepR101V3PlusD_HANet_OS8', '--city_mode', 'train', '--lr_schedule', 'poly', '--lr', '0.01', '--poly_exp', '0.9', '--hanet_lr', '0.01', '--hanet_poly_exp', '0.9', '--max_cu_epoch', '10000', '--class_uniform_pct', '0.5', '--class_uniform_tile', '1024', '--syncbn', '--sgd', '--crop_size', '768', '--scale_min', '0.5', '--scale_max', '2.0', '--rrotate', '0', '--color_aug', '0.25', '--gblur', '--max_iter', '40000', '--bs_mult', '2', '--hanet', '1', '1', '1', '1', '0', '--hanet_set', '3', '64', '3', '--hanet_pos', '2', '1', '--pos_rfactor', '2', '--dropout', '0.5', '--pos_noise', '0.5', '--aux_loss', '--date', '0103', '--exp', 'r101_os8_hanet_64_01', '--ckpt', './logs/', '--tb_path', './logs/']' returned non-zero exit status 1.

**Comment by sunghac** [comment]
Hi,
To run the script "train_r101_os8_hanet.sh", two Titan RTX GPUs are required as below.
![image](https://user-images.githubusercontent.com/34509882/91307318-c0206980-e7e8-11ea-9c99-c63595383b77.png)

If one batch goes up on one GPU, PyTorch version 1.4.0 generates the above error.
In my memory, PyTorch version 1.2.0 will not cause the error even if one batch goes up on the GPU. However, it is just a workaround.

**Comment by Uproar197** [comment]
**Thank you for answering my question.**

①
> To run the script "train_r101_os8_hanet.sh", two Titan RTX GPUs are required as below.
![](https://user-images.githubusercontent.com/34509882/91307318-c0206980-e7e8-11ea-9c99-c63595383b77.png)
**Is it means that my gpu capacity not enough, I used four 11G  gpus  ?**

②
> If one batch goes up on one GPU, PyTorch version 1.4.0 generates the above error.
> In my memory, PyTorch version 1.2.0 will not cause the error even if one batch goes up on the GPU. However, it is just a workaround.
**I will change the version of PyTorch and  try again.**

**Thanks again !!!**

**Comment by sunghac** [comment]
1. Is it means that my gpu capacity not enough, I used four 11G gpus?
> A little insufficient. Four Titan XP (12GB) are possible.
> You need to reduce the image crop size or batch number, then it will affect performance.
Thank you!!

**Comment by Uproar197** [comment]
ok, I got it . Thanks
